schemapatch:
  requiredFeatureSets:
    - ""
    - "Default"
    - "TechPreviewNoUpgrade"
    - "CustomNoUpgrade"
  mustHaveOneOfClusterProfile:
    - "ibm-cloud-managed"
    - "self-managed-high-availability"
    - "single-node-developer"
swaggerdocs:
  commentPolicy: Warn
